feat: add GitHub section component
frontendship/website pull request #26
Opened 2022-10-26 13:09 UTC by burak-balci

2022-10-26 13:28 UTC, omeersari commented
@burak-balci @eraygundogmus Responsive design için pek uygun gelmedi ama responsive design tasarımı da yok. Bunu daha sonra mı yazacağız ?

2022-10-27 17:11 UTC, muratdemirci approved these changes
LGTM

2022-10-27 17:20 UTC, eraygundogmus commented
@burak-balci Hey, Burak! Could you please update your PR with adding responsive designs?

2022-10-28 07:12 UTC, OrhanOzkercin requested changes
Could you please sync `package-lock.json` as far as I see there is no difference. So it should not be shown as a difference.

2022-10-28 07:12 UTC, OrhanOzkercin commented on components/GitHubSectionCard/GitHubSectionCard.tsx
> +              alt=""
We may want to add alt tag to images

2022-10-28 18:27 UTC, eraygundogmus commented
LGTM!

2022-10-28 18:28 UTC, eraygundogmus approved these changes

2022-10-28 18:29 UTC, merged